[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=c++17
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    sandeepmistry/LoRa@^0.8.0
    esphome/ESPAsyncWebServer-esphome@^3.0.0
    knolleary/PubSubClient@^2.8
